export const CHAT_MODELS = [
  {
    id: "council",
    name: "Council",
    shortName: "Council",
    provider: "council",
    premium: true,
    contextWindow: 200000,
  },
  {
    id: "gemini-3-flash-preview",
    name: "Flash",
    shortName: "Flash",
    provider: "gemini",
    privacy: true,
    contextWindow: 1048576,
  },
  {
    id: "gemini-3-pro-preview",
    name: "Pro",
    shortName: "Pro",
    provider: "gemini",
    privacy: true,
    contextWindow: 1048576,
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "Sonnet",
    shortName: "Sonnet",
    provider: "claude",
    contextWindow: 200000,
  },
  {
    id: "claude-opus-4-6-20260205",
    name: "Opus",
    shortName: "Opus",
    provider: "claude",
    contextWindow: 200000,
  },
  {
    id: "gpt-5.2",
    name: "GPT",
    shortName: "GPT",
    provider: "openai",
    contextWindow: 1048576,
  },
];
